`timescale 1ns / 1ps

module datapath(
    input wire clk,
    input wire rst,
    input wire Reg2Loc_id, Unconditionbranch_id, Branch_id, Memread_id, MemtoReg_id, Memwrite_id, ALUSrc_id, Regwrite_id,
    input wire [3:0] ALUop_id,
    input logic hazardmux_id, idhold_id, pchold_id,
    input logic [1:0] muxa, muxb,

    // Instruction memory pipelined request/response interface
    output wire [63:0] imem_req_addr,
    output wire        imem_req_valid,
    input  wire        imem_req_ready,

    input  wire        imem_rsp_valid,
    output wire        imem_rsp_ready,
    input  wire [63:0] imem_rsp_addr,
    input  wire [31:0] imem_rsp_data,

    output wire        imem_flush,

    // Data memory request/ack interface
    output wire [63:0] dmem_addr,
    output wire [63:0] dmem_wdata,
    output wire        dmem_we,
    output wire        dmem_re,
    input  wire        dmem_ready,
    input  wire [63:0] dmem_rdata,

    output wire [4:0] Rn_id, Rm_id,
    output logic [31:0] instruction_id,
    output logic [4:0] Rd_ex, Rd_mem,
    output logic Memread_ex, Regwrite_ex, MemtoReg_mem,
    output logic [4:0] Rm_ex, Rn_ex, Rd_wb,
    output logic Regwrite_mem, Regwrite_wb
);

    // Global stall generated by an older data-memory operation in MEM.
    wire mem_wait;

    // Branches are resolved in EX.  Keeping the decision out of ID removes the
    // instruction-decode -> register-file-read -> zero-compare -> PC feedback
    // cone that dominated pre-PnR setup timing.
    logic Branch_ex, Unconditionbranch_ex;
    logic [63:0] branch_target_ex;
    wire branch_taken_ex_raw;
    wire branch_taken_ex;

    /*==============
         IF stage
      ==============*/

    wire [63:0] pc_if, pc_next, pc_4_if;
    wire [31:0] instruction_if;

    wire imem_req_fire;
    wire imem_rsp_fire;
    wire front_stall;
    wire pc_hold_all;

    assign pc_4_if = pc_if + 64'd4;
    assign pc_next = branch_taken_ex ? branch_target_ex : pc_4_if;

    assign front_stall = pchold_id | idhold_id | mem_wait;

    assign imem_req_addr  = pc_if;
    assign imem_req_valid = !rst && !front_stall && !branch_taken_ex;
    assign imem_req_fire  = imem_req_valid && imem_req_ready;

    assign imem_rsp_ready = !rst && !front_stall && !branch_taken_ex;
    assign imem_rsp_fire  = imem_rsp_valid && imem_rsp_ready;

    // A taken EX-stage branch invalidates every younger sequential fetch.
    assign imem_flush = branch_taken_ex;

    // Sequential fetch advances only after a request handshake.  A taken branch
    // overrides the hold and redirects the PC independently of request ready.
    assign pc_hold_all = !branch_taken_ex && !imem_req_fire;

    programcounter PC (
        .clk(clk),
        .rst(rst),
        .pc_next(pc_next),
        .pchold(pc_hold_all),
        .pc(pc_if)
    );

    assign instruction_if = imem_rsp_data;

    /*==============
         ID stage
      ==============*/

    logic [63:0] pc_id;
    wire [63:0] Readdata1_id, Readdata2_id;
    wire [63:0] SE_Dtaddr_id;
    wire [63:0] branch_target_id;
    wire [5:0] shamt_id;
    wire [4:0] Rd_id;

    assign shamt_id = instruction_id[15:10];
    assign Rm_id    = Reg2Loc_id ? instruction_id[4:0] : instruction_id[20:16];
    assign Rn_id    = instruction_id[9:5];
    assign Rd_id    = instruction_id[4:0];

    // Compute the target in ID, then register it.  The EX branch decision sees
    // only registered target/data, so the PC path no longer contains this adder.
    assign branch_target_id = pc_id + (SE_Dtaddr_id << 2);

    signextension SE (
        .instruction(instruction_id),
        .SE_Dtaddr(SE_Dtaddr_id)
    );

    register REG (
        .clk(clk),
        .Rm(Rm_id),
        .Rn(Rn_id),
        .Rd(Rd_wb),
        .Regwrite(Regwrite_wb),
        .Regwritedata(Regwritedata_wb),
        .Readdata1(Readdata1_id),
        .Readdata2(Readdata2_id)
    );

    /*==============
         EX stage
      ==============*/

    logic [63:0] Readdata1_ex, Readdata2_ex, SE_Dtaddr_ex;
    logic MemtoReg_ex, Memwrite_ex, ALUSrc_ex;
    logic [3:0] ALUop_ex;
    logic [5:0] shamt_ex;

    wire [63:0] result_ex;
    wire [63:0] Readdata1_ex_mux;
    wire [63:0] Readdata2_ex_mux;
    wire [63:0] Readdata2_ex_Src;
    wire branch_zero_ex;

    assign Readdata1_ex_mux =
        (muxa == 2'b10) ? result_mem :
        (muxa == 2'b01) ? Regwritedata_wb :
                          Readdata1_ex;

    assign Readdata2_ex_mux =
        (muxb == 2'b10) ? result_mem :
        (muxb == 2'b01) ? Regwritedata_wb :
                          Readdata2_ex;

    assign Readdata2_ex_Src = ALUSrc_ex ? SE_Dtaddr_ex : Readdata2_ex_mux;

    // CBZ uses the same forwarded EX operand path as ordinary ALU consumers.
    // An older MEM stall must complete before a branch is allowed to redirect.
    assign branch_zero_ex      = (Readdata2_ex_mux == 64'd0);
    assign branch_taken_ex_raw = Unconditionbranch_ex | (Branch_ex && branch_zero_ex);
    assign branch_taken_ex     = !mem_wait && branch_taken_ex_raw;

    // Compatibility/debug name retained for existing waveform/testbench probes.
    // Functionally the branch source is now EX, despite the historical suffix.
    wire PCSrc_id;
    assign PCSrc_id = branch_taken_ex;

    ALU ALU (
        .ALUop(ALUop_ex),
        .Readdata1(Readdata1_ex_mux),
        .Readdata2(Readdata2_ex_Src),
        .shamt(shamt_ex),
        .result(result_ex)
    );

    /*==============
         MEM stage
      ==============*/

    logic Memread_mem, Memwrite_mem;
    logic [63:0] result_mem;
    logic [63:0] Readdata2_mem_mux;
    wire [63:0] Readmemdata_mem;

    assign dmem_addr  = result_mem;
    assign dmem_wdata = Readdata2_mem_mux;
    assign dmem_we    = Memwrite_mem;
    assign dmem_re    = Memread_mem;

    assign Readmemdata_mem = dmem_rdata;

    wire mem_access;
    assign mem_access = Memread_mem | Memwrite_mem;
    assign mem_wait   = mem_access && !dmem_ready;

    /*==============
         WB stage
      ==============*/

    logic MemtoReg_wb;
    logic [63:0] result_wb;
    logic [63:0] Readmemdata_wb;
    logic [63:0] Regwritedata_wb;

    always_comb begin
        Regwritedata_wb = MemtoReg_wb ? Readmemdata_wb : result_wb;
    end

    /*==============
         Pipeline registers
      ==============*/

    // IF/ID: hold on data/memory stalls, flush on a taken EX branch.
    always @(posedge clk) begin
        if (rst) begin
            instruction_id <= 32'd0;
            pc_id           <= 64'd0;
        end
        else if (mem_wait) begin
            // hold
        end
        else if (branch_taken_ex) begin
            instruction_id <= 32'd0;
            pc_id           <= 64'd0;
        end
        else if (idhold_id) begin
            // hold
        end
        else if (imem_rsp_fire) begin
            instruction_id <= instruction_if;
            pc_id           <= imem_rsp_addr;
        end
        else begin
            instruction_id <= 32'd0;
            pc_id           <= 64'd0;
        end
    end

    // ID/EX: a load-use interlock or taken older branch injects a bubble.
    always @(posedge clk) begin
        if (rst) begin
            Readdata1_ex       <= 64'd0;
            Readdata2_ex       <= 64'd0;
            Memread_ex         <= 1'b0;
            MemtoReg_ex        <= 1'b0;
            Memwrite_ex        <= 1'b0;
            ALUSrc_ex          <= 1'b0;
            Regwrite_ex        <= 1'b0;
            ALUop_ex           <= 4'd0;
            shamt_ex           <= 6'd0;
            Rm_ex              <= 5'd0;
            Rn_ex              <= 5'd0;
            Rd_ex              <= 5'd0;
            SE_Dtaddr_ex       <= 64'd0;
            Branch_ex          <= 1'b0;
            Unconditionbranch_ex <= 1'b0;
            branch_target_ex   <= 64'd0;
        end
        else if (mem_wait) begin
            // hold
        end
        else if (branch_taken_ex || idhold_id) begin
            Readdata1_ex       <= 64'd0;
            Readdata2_ex       <= 64'd0;
            Memread_ex         <= 1'b0;
            MemtoReg_ex        <= 1'b0;
            Memwrite_ex        <= 1'b0;
            ALUSrc_ex          <= 1'b0;
            Regwrite_ex        <= 1'b0;
            ALUop_ex           <= 4'd0;
            shamt_ex           <= 6'd0;
            Rm_ex              <= 5'd0;
            Rn_ex              <= 5'd0;
            Rd_ex              <= 5'd0;
            SE_Dtaddr_ex       <= 64'd0;
            Branch_ex          <= 1'b0;
            Unconditionbranch_ex <= 1'b0;
            branch_target_ex   <= 64'd0;
        end
        else begin
            Readdata1_ex       <= Readdata1_id;
            Readdata2_ex       <= Readdata2_id;
            Memread_ex         <= Memread_id;
            MemtoReg_ex        <= MemtoReg_id;
            Memwrite_ex        <= Memwrite_id;
            ALUSrc_ex          <= ALUSrc_id;
            Regwrite_ex        <= Regwrite_id;
            ALUop_ex           <= ALUop_id;
            shamt_ex           <= shamt_id;
            Rm_ex              <= Rm_id;
            Rn_ex              <= Rn_id;
            Rd_ex              <= Rd_id;
            SE_Dtaddr_ex       <= SE_Dtaddr_id;
            Branch_ex          <= Branch_id;
            Unconditionbranch_ex <= Unconditionbranch_id;
            branch_target_ex   <= branch_target_id;
        end
    end

    // EX/MEM: only an older memory wait freezes this stage.
    always @(posedge clk) begin
        if (rst) begin
            Memread_mem        <= 1'b0;
            MemtoReg_mem       <= 1'b0;
            Memwrite_mem       <= 1'b0;
            Regwrite_mem       <= 1'b0;
            Rd_mem             <= 5'd0;
            result_mem         <= 64'd0;
            Readdata2_mem_mux  <= 64'd0;
        end
        else if (mem_wait) begin
            // hold
        end
        else begin
            Memread_mem        <= Memread_ex;
            MemtoReg_mem       <= MemtoReg_ex;
            Memwrite_mem       <= Memwrite_ex;
            Regwrite_mem       <= Regwrite_ex;
            Rd_mem             <= Rd_ex;
            result_mem         <= result_ex;
            Readdata2_mem_mux  <= Readdata2_ex_mux;
        end
    end

    // MEM/WB: when MEM waits, retire the current WB once and inject a bubble so
    // the same architectural write cannot repeat every wait-state cycle.
    always @(posedge clk) begin
        if (rst) begin
            MemtoReg_wb     <= 1'b0;
            Regwrite_wb     <= 1'b0;
            Rd_wb           <= 5'd0;
            result_wb       <= 64'd0;
            Readmemdata_wb  <= 64'd0;
        end
        else if (mem_wait) begin
            MemtoReg_wb     <= 1'b0;
            Regwrite_wb     <= 1'b0;
            Rd_wb           <= 5'd0;
            result_wb       <= 64'd0;
            Readmemdata_wb  <= 64'd0;
        end
        else begin
            MemtoReg_wb     <= MemtoReg_mem;
            Regwrite_wb     <= Regwrite_mem;
            Rd_wb           <= Rd_mem;
            result_wb       <= result_mem;
            Readmemdata_wb  <= Readmemdata_mem;
        end
    end

    // Kept only so legacy debug probes can still observe the three identical
    // load-use control outputs.  Functional bubble insertion is keyed by idhold.
    wire unused_hazardmux = hazardmux_id;

endmodule
